# Generated by Django 3.0.8 on 2020-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fooditem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='restaurant_picture')),
                ('fooditems', models.ManyToManyField(to='fooditem.FoodItem')),
            ],
        ),
    ]
