# Generated by Django 3.0.8 on 2020-08-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200829_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.IntegerField(default=1),
        ),
    ]
