# Generated by Django 3.0.8 on 2020-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200830_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_no',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
